server:
  port: 8082

spring:
  application:
    name: order-service

custom:
  message: Hello from Config Server ... 🚀

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
